version: "3.9"

services:
  api:
    image: ramecnt/flask_note_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:80"
    volumes:
      - .configs/docker_config.py:/code/configs/default_config.py
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
